//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using UnityEngine.Localization.Settings;

namespace FantomLis.BoomboxExtended {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BoomboxLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture =>
            CultureInfo.GetCultureInfo(LocalizationSettings.SelectedLocale.Identifier.CultureInfo.LCID);
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BoomboxLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FantomLis.BoomboxExtended.BoomboxLocalization", typeof(BoomboxLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boombox Battery Capacity (-1 to infinite).
        /// </summary>
        internal static string BatteryCapacitySetting {
            get {
                return ResourceManager.GetString("BatteryCapacitySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boombox.
        /// </summary>
        internal static string BoomboxName {
            get {
                return ResourceManager.GetString("BoomboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boombox Price.
        /// </summary>
        internal static string BoomboxPriceSetting {
            get {
                return ResourceManager.GetString("BoomboxPriceSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string BoomboxVolume {
            get {
                return ResourceManager.GetString("BoomboxVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] Switch Song.
        /// </summary>
        internal static string ClickSwitchToolTip {
            get {
                return ResourceManager.GetString("ClickSwitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music loading finished!.
        /// </summary>
        internal static string MusicLoadedAlert {
            get {
                return ResourceManager.GetString("MusicLoadedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} files.
        /// </summary>
        internal static string MusicLoadedAlertDesc {
            get {
                return ResourceManager.GetString("MusicLoadedAlertDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Selection Method.
        /// </summary>
        internal static string MusicSelectionMethodSetting {
            get {
                return ResourceManager.GetString("MusicSelectionMethodSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load localization ({0}).
        /// </summary>
        internal static string NoLocalizationStringError {
            get {
                return ResourceManager.GetString("NoLocalizationStringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Music.
        /// </summary>
        internal static string NoMusicHelmetAlert {
            get {
                return ResourceManager.GetString("NoMusicHelmetAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Loaded Music .
        /// </summary>
        internal static string NoMusicLoaded {
            get {
                return ResourceManager.GetString("NoMusicLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] Scroll Songs.
        /// </summary>
        internal static string ScrollSwitchToolTip {
            get {
                return ResourceManager.GetString("ScrollSwitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string SelectionMethod_Default {
            get {
                return ResourceManager.GetString("SelectionMethod_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string SelectionMethod_Original {
            get {
                return ResourceManager.GetString("SelectionMethod_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Wheel.
        /// </summary>
        internal static string SelectionMethod_ScrollWheel {
            get {
                return ResourceManager.GetString("SelectionMethod_ScrollWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection UI (mouse) .
        /// </summary>
        internal static string SelectionMethod_SelectionUIMouse {
            get {
                return ResourceManager.GetString("SelectionMethod_SelectionUIMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection UI (scroll).
        /// </summary>
        internal static string SelectionMethod_SelectionUIScroll {
            get {
                return ResourceManager.GetString("SelectionMethod_SelectionUIScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song loaded.
        /// </summary>
        internal static string SingleSongLoadedAlert {
            get {
                return ResourceManager.GetString("SingleSongLoadedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] Open Boombox UI.
        /// </summary>
        internal static string UISwitchToolTip {
            get {
                return ResourceManager.GetString("UISwitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] Play song.
        /// </summary>
        internal static string UseToolTip {
            get {
                return ResourceManager.GetString("UseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boombox Verbose Log.
        /// </summary>
        internal static string VerboseLoggingSetting {
            get {
                return ResourceManager.GetString("VerboseLoggingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boombox Volume Down Key.
        /// </summary>
        internal static string VolumeDownSetting {
            get {
                return ResourceManager.GetString("VolumeDownSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] Volume down.
        /// </summary>
        internal static string VolumeDownToolTip {
            get {
                return ResourceManager.GetString("VolumeDownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boombox Volume Up Key.
        /// </summary>
        internal static string VolumeUpSetting {
            get {
                return ResourceManager.GetString("VolumeUpSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] Volume up.
        /// </summary>
        internal static string VolumeUpToolTip {
            get {
                return ResourceManager.GetString("VolumeUpToolTip", resourceCulture);
            }
        }
    }
}
