//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantomLis.BoomboxExtended {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FantomLis.BoomboxExtended.LocalizationStrings", typeof(LocalizationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Boombox.
        /// </summary>
        internal static string Boombox {
            get {
                return ResourceManager.GetString("Boombox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @BatteryCapacity.
        /// </summary>
        internal static string Boombox_BatteryCapacitySetting {
            get {
                return ResourceManager.GetString("Boombox_BatteryCapacitySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @BoomboxPrice.
        /// </summary>
        internal static string Boombox_BoomboxPriceSetting {
            get {
                return ResourceManager.GetString("Boombox_BoomboxPriceSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @Boombox_ClickSwitchToolTip.
        /// </summary>
        internal static string Boombox_ClickSwitchToolTip {
            get {
                return ResourceManager.GetString("Boombox_ClickSwitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MusicLoadedAlert.
        /// </summary>
        internal static string Boombox_MusicLoadedAlert {
            get {
                return ResourceManager.GetString("Boombox_MusicLoadedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MusicLoadedAlertDesc {0}.
        /// </summary>
        internal static string Boombox_MusicLoadedAlertDesc {
            get {
                return ResourceManager.GetString("Boombox_MusicLoadedAlertDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MusicSelectionMethod.
        /// </summary>
        internal static string Boombox_MusicSelectionMethodSetting {
            get {
                return ResourceManager.GetString("Boombox_MusicSelectionMethodSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @NoLocalizationString {0}.
        /// </summary>
        internal static string Boombox_NoLocalizationStringError {
            get {
                return ResourceManager.GetString("Boombox_NoLocalizationStringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @Boombox_ScrollSwitchToolTip.
        /// </summary>
        internal static string Boombox_ScrollSwitchToolTip {
            get {
                return ResourceManager.GetString("Boombox_ScrollSwitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Default.
        /// </summary>
        internal static string Boombox_SelectionMethod_Default {
            get {
                return ResourceManager.GetString("Boombox_SelectionMethod_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Original.
        /// </summary>
        internal static string Boombox_SelectionMethod_Original {
            get {
                return ResourceManager.GetString("Boombox_SelectionMethod_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ScrollWheel.
        /// </summary>
        internal static string Boombox_SelectionMethod_ScrollWheel {
            get {
                return ResourceManager.GetString("Boombox_SelectionMethod_ScrollWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SelectionUINoScroll.
        /// </summary>
        internal static string Boombox_SelectionMethod_SelectionUIMouse {
            get {
                return ResourceManager.GetString("Boombox_SelectionMethod_SelectionUIMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SelectionUI.
        /// </summary>
        internal static string Boombox_SelectionMethod_SelectionUIScroll {
            get {
                return ResourceManager.GetString("Boombox_SelectionMethod_SelectionUIScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SingleSongLoadedAlert.
        /// </summary>
        internal static string Boombox_SingleSongLoadedAlert {
            get {
                return ResourceManager.GetString("Boombox_SingleSongLoadedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @Boombox_UISwitchToolTip.
        /// </summary>
        internal static string Boombox_UISwitchToolTip {
            get {
                return ResourceManager.GetString("Boombox_UISwitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @Boombox_UseToolTip.
        /// </summary>
        internal static string Boombox_UseToolTip {
            get {
                return ResourceManager.GetString("Boombox_UseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VerboseLogging.
        /// </summary>
        internal static string Boombox_VerboseLoggingSetting {
            get {
                return ResourceManager.GetString("Boombox_VerboseLoggingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Volume.
        /// </summary>
        internal static string Boombox_Volume {
            get {
                return ResourceManager.GetString("Boombox_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VolumeDownSetting.
        /// </summary>
        internal static string Boombox_VolumeDownSetting {
            get {
                return ResourceManager.GetString("Boombox_VolumeDownSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @Boombox_VolumeDownToolTip.
        /// </summary>
        internal static string Boombox_VolumeDownToolTip {
            get {
                return ResourceManager.GetString("Boombox_VolumeDownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VolumeUpSetting.
        /// </summary>
        internal static string Boombox_VolumeUpSetting {
            get {
                return ResourceManager.GetString("Boombox_VolumeUpSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @Boombox_VolumeUpToolTip.
        /// </summary>
        internal static string Boombox_VolumeUpToolTip {
            get {
                return ResourceManager.GetString("Boombox_VolumeUpToolTip", resourceCulture);
            }
        }
    }
}
