//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantomLis.BoomboxExtended {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FantomLis.BoomboxExtended.LocalizationStrings", typeof(LocalizationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Boombox.
        /// </summary>
        internal static string Boombox {
            get {
                return ResourceManager.GetString("Boombox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @Boombox_ClickSwitchTrackToolTip.
        /// </summary>
        internal static string Boombox_ClickSwitchToolTip {
            get {
                return ResourceManager.GetString("Boombox_ClickSwitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @Boombox_ScrollSwitchTrackToolTip.
        /// </summary>
        internal static string Boombox_ScrollSwitchToolTip {
            get {
                return ResourceManager.GetString("Boombox_ScrollSwitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @Boombox_UISwitchTrackToolTip.
        /// </summary>
        internal static string Boombox_UISwitchToolTip {
            get {
                return ResourceManager.GetString("Boombox_UISwitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @Boombox_UseToolTip.
        /// </summary>
        internal static string Boombox_UseToolTip {
            get {
                return ResourceManager.GetString("Boombox_UseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @Boombox_VolumeDownToolTip.
        /// </summary>
        internal static string Boombox_VolumeDownToolTip {
            get {
                return ResourceManager.GetString("Boombox_VolumeDownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @Boombox_VolumeUpToolTip.
        /// </summary>
        internal static string Boombox_VolumeUpToolTip {
            get {
                return ResourceManager.GetString("Boombox_VolumeUpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Volume.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
    }
}
