//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using UnityEngine.Localization.Settings;

namespace FantomLis.BoomboxExtended.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BoomboxLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture =>
            CultureInfo.GetCultureInfo(LocalizationSettings.SelectedLocale.Identifier.CultureInfo.LCID);
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BoomboxLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(typeof(BoomboxLocalization).FullName, typeof(BoomboxLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @BatteryCapacitySetting.
        /// </summary>
        internal static string BatteryCapacitySetting {
            get {
                return ResourceManager.GetString("BatteryCapacitySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @BatteryCapacityTip.
        /// </summary>
        internal static string BatteryCapacitySettingTip {
            get {
                return ResourceManager.GetString("BatteryCapacitySettingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @BoomboxName.
        /// </summary>
        internal static string BoomboxName {
            get {
                return ResourceManager.GetString("BoomboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @BoomboxPriceSetting.
        /// </summary>
        internal static string BoomboxPriceSetting {
            get {
                return ResourceManager.GetString("BoomboxPriceSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @BoomboxVolume.
        /// </summary>
        internal static string BoomboxVolume {
            get {
                return ResourceManager.GetString("BoomboxVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ChangesApplyAfterRestartDesc.
        /// </summary>
        internal static string ChangesApplyAfterRestartDesc {
            get {
                return ResourceManager.GetString("ChangesApplyAfterRestartDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ChangesApplyAfterRestartTitle.
        /// </summary>
        internal static string ChangesApplyAfterRestartTitle {
            get {
                return ResourceManager.GetString("ChangesApplyAfterRestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @ClickSwitchToolTip.
        /// </summary>
        internal static string ClickSwitchToolTip {
            get {
                return ResourceManager.GetString("ClickSwitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MusicLoadedAlert.
        /// </summary>
        internal static string MusicLoadedAlert {
            get {
                return ResourceManager.GetString("MusicLoadedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MusicLoadedAlertDesc {0}.
        /// </summary>
        internal static string MusicLoadedAlertDesc {
            get {
                return ResourceManager.GetString("MusicLoadedAlertDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MusicNotLoaded.
        /// </summary>
        internal static string MusicNotLoaded {
            get {
                return ResourceManager.GetString("MusicNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MusicSelectionMethodSetting.
        /// </summary>
        internal static string MusicSelectionMethodSetting {
            get {
                return ResourceManager.GetString("MusicSelectionMethodSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @NoLocalizationStringError {0}.
        /// </summary>
        internal static string NoLocalizationStringError {
            get {
                return ResourceManager.GetString("NoLocalizationStringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @NoMusic.
        /// </summary>
        internal static string NoMusicHelmetAlert {
            get {
                return ResourceManager.GetString("NoMusicHelmetAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @NoMusicLoaded.
        /// </summary>
        internal static string NoMusicLoaded {
            get {
                return ResourceManager.GetString("NoMusicLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PauseMusicSetting.
        /// </summary>
        internal static string PauseMusicSetting {
            get {
                return ResourceManager.GetString("PauseMusicSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @ScrollSwitchToolTip.
        /// </summary>
        internal static string ScrollSwitchToolTip {
            get {
                return ResourceManager.GetString("ScrollSwitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SM_Default.
        /// </summary>
        internal static string SelectionMethod_Default {
            get {
                return ResourceManager.GetString("SelectionMethod_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SM_Original.
        /// </summary>
        internal static string SelectionMethod_Original {
            get {
                return ResourceManager.GetString("SelectionMethod_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SM_ScrollWheel.
        /// </summary>
        internal static string SelectionMethod_ScrollWheel {
            get {
                return ResourceManager.GetString("SelectionMethod_ScrollWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SM_SelectionUINoScroll.
        /// </summary>
        internal static string SelectionMethod_SelectionUIMouse {
            get {
                return ResourceManager.GetString("SelectionMethod_SelectionUIMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SM_SelectionUI.
        /// </summary>
        internal static string SelectionMethod_SelectionUIScroll {
            get {
                return ResourceManager.GetString("SelectionMethod_SelectionUIScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SingleSongLoadedAlert.
        /// </summary>
        internal static string SingleSongLoadedAlert {
            get {
                return ResourceManager.GetString("SingleSongLoadedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @UISwitchToolTip.
        /// </summary>
        internal static string UISwitchToolTip {
            get {
                return ResourceManager.GetString("UISwitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @UseToolTip.
        /// </summary>
        internal static string UseToolTip {
            get {
                return ResourceManager.GetString("UseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VerboseLoggingSetting.
        /// </summary>
        internal static string VerboseLoggingSetting {
            get {
                return ResourceManager.GetString("VerboseLoggingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VolumeDownSetting.
        /// </summary>
        internal static string VolumeDownSetting {
            get {
                return ResourceManager.GetString("VolumeDownSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @VolumeDownToolTip.
        /// </summary>
        internal static string VolumeDownToolTip {
            get {
                return ResourceManager.GetString("VolumeDownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VolumeStepSetting.
        /// </summary>
        internal static string VolumeStepSetting {
            get {
                return ResourceManager.GetString("VolumeStepSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @VolumeUpSetting.
        /// </summary>
        internal static string VolumeUpSetting {
            get {
                return ResourceManager.GetString("VolumeUpSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{key}] @VolumeUpToolTip.
        /// </summary>
        internal static string VolumeUpToolTip {
            get {
                return ResourceManager.GetString("VolumeUpToolTip", resourceCulture);
            }
        }
    }
}
